### ISSUE TITLE
Standardizing events per tool

### ISSUE THREAD

**Issue by eliasyishak** [eliasyishak/dash_analytics#25]
Discussion from @bwilkerson

It looks like there's a master list of event names to pass into `sendEvent`. I had assumed that these would be tool-specific, but that appears to not be the case. How are we going to prevent multiple tools from using the same event name for different purposes? Will we use a naming convention, such as 'toolName_eventName'? Or will the tool name and event name be joined automatically so that we don't need to worry about collisions?

**Comment by eliasyishak** [comment]
This is also something under consideration. I am working with the enhanced enums for each dash related tool to see if I can link the events to their respective tool. It may end up being the case that we use classes for each tool instead of enums.

If you have an idea for how we can do this, I'd love to see any example

**Comment by bwilkerson** [comment]
I'd need to know more about the requirements / constraints you're trying to meet.

Do we want to have a fixed (controlled) list of tools that can report? In other words, if we decide to add a `dart prune` command, should we need to edit this package to add that tool to the list? (I'm assuming that each command under `dart` and `flutter` is considered a separate tool, which might not be valid. I assume you'll add some documentation that defines basic concepts like what we mean by 'tool' and 'event' so that we can stay consistent over time.)

Do we want to have a fixed (controlled) list of events for each tool, or would it be better for each tool to control the list of events that it reports so that changes are made locally in the tool's code rather than in this shared package?

There are advantages and disadvantages of each of these choices, and there are clearly implementation implications as well.
